language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install cltk
  - pip install coveralls
  - pip install nose

# command to run tests
script:
  - pie-extended install-addons lasla
  - nosetests ./tests --with-coverage --cover-package=pie_extended --cover-xml --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls